apiVersion: v1
kind: Namespace
metadata:
  name: telegram-bots
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hhh-diff-bot-state-pvc
  namespace: telegram-bots
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: v1
kind: Secret
metadata:
  name: hhh-diff-bot-secrets
  namespace: telegram-bots
type: Opaque
data:
  BOT_TOKEN: "{{BOT_TOKEN}}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hhh-diff-bot
  namespace: telegram-bots
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hhh-diff-bot
  template:
    metadata:
      labels:
        app: hhh-diff-bot
        dockertag: {{DOCKER_TAG}}
    spec:
      containers:
        - name: hhh-diff-bot
          image: torbencarstens/hhh-diff-bot:{{DOCKER_TAG}}
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: hhh-diff-bot-secrets
          volumeMounts:
            - mountPath: "/data"
              name: hhh-diff-bot-state-volume
      volumes:
        - name: hhh-diff-bot-state-volume
          persistentVolumeClaim:
            claimName: hhh-diff-bot-state-pvc

